<a href="https://colab.research.google.com/github/saksham3232/DS-YT/blob/main/numpy/array_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Numpy Indexing and Slicing of Vectors

In [4]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[9]

np.int64(20)

In [6]:
arr[3::2]

array([14, 16, 18, 20])

# NUMPY Indexing and Slicing of Matrix

In [8]:
arr = np.arange(1, 31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[5]

array([26, 27, 28, 29, 30])

In [15]:
arr[0,0]

np.int64(1)

In [16]:
arr[0,4]

np.int64(5)

In [19]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
slice = arr[1:3, 1:3]
slice

array([[ 7,  8],
       [12, 13]])

In [27]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [28]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [30]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [32]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])