<a href="https://colab.research.google.com/github/saksham3232/DS-YT/blob/main/numpy/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Array Operations

## Arithmetic Opeations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a2

array([ 6,  7,  8,  9, 10])

In [6]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [8]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [13]:
l = [10,20,30,40]
arr = np.array(l)

In [15]:
arr + 10

array([20, 30, 40, 50])

In [16]:
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [19]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# Deep and Shallow Copy

In [34]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a[4:6] * 10

array([50, 60])

In [38]:
a
b = a.copy()

In [39]:
b[0] = 99

In [40]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Operations

In [42]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [43]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[5, 6],
       [7, 8]])

In [46]:
A * B

array([[ 5, 12],
       [21, 32]])

In [47]:
A @ B

array([[19, 22],
       [43, 50]])

In [48]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [49]:
A

array([[1, 2],
       [3, 4]])

In [50]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

## Stacking Array

In [53]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [54]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Spliting Array

In [58]:
c = np.arange(1, 17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
np.hsplit(c, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [60]:
np.vsplit(c, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]