<a href="https://colab.research.google.com/github/saksham3232/DS-YT/blob/main/numpy/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Valid Sudoku

In [10]:
import numpy as np

In [18]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [19]:
b = np.sum(s, axis=1)

In [21]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
for i in b:
  if i != 45:
    print("Sudoku is not valid")
    break
else:
  print("For row it is valid")

For row it is valid


In [23]:
c = np.sum(s, axis=0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [24]:
for i in c:
  if i != 45:
    print("Sudoku is not valid")
    break
else:
  print("For col it is valid")

For col it is valid


In [34]:
for i in range(0, 9, 3):
  for j in range(0, 9, 3):
    n = s[i:i+3, j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


## General Questions

In [36]:
import numpy as np

In [59]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [60]:
data.shape #shape

(5, 3)

In [61]:
np.mean(data[:,0]) #avg age of student

np.float64(18.4)

In [62]:
data[:,1] #math marks of all student

array([85, 92, 76, 65, 90])

In [63]:
np.max(data[:, 2]) #max science marks

np.int64(95)

In [64]:
# Get details of the student who scored more than 90 in math
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [65]:
#Increase math marks of all students by 5
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [68]:
#Find how many students are younger than 19
len(data[data[:, 0] < 19])

3

In [70]:
#Calculate the avg marks of each subject
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [74]:
#Get data of students who scored atleast 80 in both subjects
data[(data[:,1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [75]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [76]:
#Replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])